name: Common Job

on:
  workflow_call:
    secrets:
      PUBLISH_PACKAGES:
        required: true
      AWS_ECR_ACCESS_KEY_ID:
        required: true
      AWS_ECR_SECRET_ACCESS_KEY:
        required: true
      AWS_ECR_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ENV_FILE: .env
      GITHUB_ACCESS_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
    name: Build and deploy the docker image to ECR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Read the env file and expose the environment variables inside the gh action job
      - name: Environment - Load the env variables from the env file
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Download all the required jar files
        run: make jars-get

      - name: AWS - Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: ECR - Login
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Docker - Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Docker - Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          context: .
          tags: "${{ steps.ecr-login.outputs.registry }}/${{ github.event.repository.name }}:${{ env.VERSION }},${{ steps.ecr-login.outputs.registry }}/${{ github.event.repository.name }}:latest, ${{ steps.ecr-login.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}"
