name: Common Job

on:
  workflow_call:
    secrets:
      PUBLISH_PACKAGES:
        required: true
      AWS_ECR_ACCESS_KEY_ID:
        required: true
      AWS_ECR_SECRET_ACCESS_KEY:
        required: true
      AWS_ECR_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ENV_FILE: .env
      GITHUB_ACCESS_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
    name: Build and deploy the docker image to ECR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker - Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          context: .
          tags: "${{ steps.ecr-login.outputs.registry }}/caching_issues:latest, ${{ steps.ecr-login.outputs.registry }}/caching_issues:${{ github.sha }}"
