name: Pull Requests

on:
  pull_request:
  push:
    tags:
      - '**'
env:
  PINO_LOG_LEVEL: 'error'

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    secrets:
      PUBLISH_PACKAGES: ${{ secrets.PUBLISH_PACKAGES }}
      AWS_ECR_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
      AWS_ECR_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
      AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
