name: Pull Requests

on:
  pull_request:
  push:
    tags:
      - '**'
env:
  PINO_LOG_LEVEL: 'error'

jobs:
  build:
    uses: ./.github/workflows/deploy.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
